{{ if .Functions -}}
app_bins = {{ range $r, $func := .Functions -}}{{ range $f := $func }}bin{{ if $r }}/{{$r}}{{ end }}/{{ $f.Handler }} {{ end }}{{ end }}
app_debugs = {{ range $r, $func := .Functions -}}{{ range $f := $func }}debug{{ if $r }}/{{$r}}{{ end }}/{{ $f.Handler }} {{ end }}{{ end }}
{{- end }}

bin/% : functions/%/main.go
		env GOOS=linux go build -ldflags="-s -w" -o $@ $<

debug/%: functions/%/main.go
		 env GOARCH=amd64 GOOS=linux go build -gcflags='-N -l' -o $@ $<

build: vendor {{ if .Functions }}| $(app_bins){{ end }}

debug: vendor {{ if .Functions }}| $(app_debugs){{ end }}

vendor: Gopkg.toml
	    dep ensure